name: Validate and Deploy SQL Scripts

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  validate_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate SQL scripts (all folders)
        run: |
          $sqlFiles = Get-ChildItem -Path "${{ github.workspace }}" -Filter *.sql -Recurse
          if (-not $sqlFiles) {
            Write-Host "No SQL files found."
            exit 0
          }

          foreach ($file in $sqlFiles) {
            Write-Host "Checking SQL syntax for $($file.FullName)"
            try {
              sqlcmd -S "${{ secrets.SQL_SERVER }}" `
                     -U "${{ secrets.SQL_USER }}" `
                     -P "${{ secrets.SQL_PASSWORD }}" `
                     -i $file.FullName -b
              Write-Host "$($file.Name) passed syntax check."
            } catch {
              Write-Host "Syntax error in $($file.Name)"
              exit 1
            }
          }

      - name: Deploy SQL scripts (all folders)
        if: success()
        run: |
          $sqlFiles = Get-ChildItem -Path "${{ github.workspace }}" -Filter *.sql -Recurse
          foreach ($file in $sqlFiles) {
            Write-Host "Deploying $($file.FullName)"
            try {
              sqlcmd -S "${{ secrets.SQL_SERVER }}" `
                     -U "${{ secrets.SQL_USER }}" `
                     -P "${{ secrets.SQL_PASSWORD }}" `
                     -i $file.FullName -b
              Write-Host "$($file.Name) deployed successfully."
            } catch {
              Write-Host "Failed to deploy $($file.Name)"
              exit 1
            }
          }
