name: CI/CD for SQL and PowerShell

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test Scripts
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Validate PowerShell scripts
      run: |
        Get-ChildItem -Path "${{ github.workspace }}/scripts" -Filter *.ps1 | ForEach-Object {
          Write-Host "Running $($_.Name)"
          pwsh $_.FullName 
        }
    
    - name: Validate SQL scripts
      run: |
        $sqlPath = "${{ github.workspace }}/ddl/v1.0"
        Get-ChildItem -Path $sqlPath -Filter *.sql | ForEach-Object {
          Write-Host "Checking SQL syntax for $($_.Name)"
          try {
            sqlcmd -S "${{ secrets.DB_SERVER }}" -U "${{ secrets.DB_USER }}" -P "${{ secrets.DB_PASS }}" -i $_.FullName -b
            Write-Host "$($_.Name) passed syntax check."
          } catch {
            Write-Host "Syntax error in $($_.Name): $_"
            exit 1
            }
          }
        

  deploy:
    name: Deploy Scripts
    needs: test
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run PowerShell scripts
      run: |
        Get-ChildItem -Path ./scripts -Filter *.ps1 | ForEach-Object {
          Write-Host "Running $_"
          pwsh $_.FullName
        }

    - name: Deploy SQL scripts
      run: |
        Get-ChildItem -Path ./sql -Filter *.sql | ForEach-Object {
          Write-Host "Deploying $_"
          sqlcmd -S ${{ secrets.DB_SERVER }} -U ${{ secrets.DB_USER }} -P ${{ secrets.DB_PASS }} -i $_.FullName
        }
