name: DB Validation
on:
  push:
    branches:
       - main
jobs:
    validate:
      runs-on: windows-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
  
        - name: Setup SQL Server LocalDB
          run: |
            sqllocaldb create MSSQLLocalDB
            sqllocaldb start MSSQLLocalDB
  
        - name: Validate SQL syntax
          shell: pwsh
          run: |
            $ErrorActionPreference = "Continue"
            $sqlFiles = Get-ChildItem -Path "${{ github.workspace }}" -Recurse -Filter *.sql
            
            if ($sqlFiles.Count -eq 0) {
                Write-Host "No SQL files found."
                exit 0
            }
  
            $allPassed = $true
            foreach ($file in $sqlFiles) {
                Write-Host "Validating $($file.FullName)..."
                
                $result = sqlcmd -S "(localdb)\MSSQLLocalDB" -d master -i $file.FullName -b -X -e 2>&1
                
                if ($LASTEXITCODE -ne 0) {
                    Write-Host "Syntax error in: $($file.Name)"
                    Write-Host $result
                    $allPassed = $false
                } else {
                    Write-Host "Syntax OK: $($file.Name)"
                }
            }
  
            if (-not $allPassed) {
                exit 1
            } else {
                Write-Host "All SQL scripts passed syntax validation!"
            }
  
  
       
       
